---
title: "Graficos no R Commander"
author: "Gabriela, Matheus, Vitor"
date: "03/05/2020"
output: html_document
---

Aqui, ensinaremos a fazer gráficos usando o RCommander, interface do R que permite análise de dados sem o uso direto de programação. Para começar, deve-se ter o RCommander instalado e o carregar.


### Gráfico de Setores

Depois de ﬁxar o banco de dados no RCommander, vá em Gráﬁcos > Gráﬁcos de Pizza selecionar a variável desejada e clique em 'OK' que seu gráﬁco será gerado. Ao lado das opções das variáveis é possível escolher os nomes dos eixos (o que não custuma ser necessário em gráﬁcos de setores) e o título.

### Gráfico de Barras

Depois de ﬁxar o banco de dados no RCommander, vá em Gráﬁcos > Gráﬁcos de Barras indique a variável desejada e a partir de qual será categorizada e clique em OK que seu gráﬁco será gerado. Só é possível gerar gráﬁcos de barras que relacionam duas variáveis. Para "desempilhar" os gráficos, vá em Opções > Estilo de barras agrupadas > Lado a lado (paralelo).

### Gráfico de Dispersão

Depois de indicar o banco de dados no RCommander, vá em Gráﬁcos > Diagrama de Dispersão. Escolha as variáveis de interesse e clique em OK que seu gráfico será gerado.

### Boxplot

Depois de deﬁnir o banco de dados no RCommander, basta ir em Gráﬁcos > Boxplot, escolher a variável desejada e clicar em OK e o gráfico será gerado. Também é possível fazer um boxplot relecionando duas variáveis: para isso, antes de gerar o boxplot clique em "Gráﬁco por grupos" e selecione a variável de interesse.

### Histograma

Depois de indicar o banco de dados no RCommander, basta ir em Gráﬁcos > Histograma, selecionar a variável desejada e clicar em OK  para gerar um histograma.



